FROM golang:1.16-buster as builder

LABEL vendor="TenxCloud Incorporated" \
      maintainer=weiwei@tenxcloud.com

ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /go/src/github.com/kelseyhightower && cd /go/src/github.com/kelseyhightower && git clone https://github.com/kelseyhightower/confd.git && cd confd && git checkout -b v0.16.0 v0.16.0 \
    && CGO_ENABLED=0 GO111MODULE=off GOOS=linux GOARCH=mips64le go build -ldflags "-w -s -X main.GitSHA=7217b0c -X main.Version=v0.16.0" -o /confd .

FROM mips64le/debian:bullseye-slim
COPY --from=builder /confd /confd
