apiVersion: v1
kind: Pod
metadata:
    name: haproxy-master21
spec:
  containers:
  - image: 192.168.1.52/system_containers/haproxy-amd64:2.1.4
    command:
    - haproxy
    args: ["-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
    imagePullPolicy: IfNotPresent
    name: haproxy
    volumeMounts:
    - mountPath: /usr/local/etc/haproxy
      name: config
  enableServiceLinks: true
  hostNetwork: true
  priority: 0
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /etc/kubernetes/haproxy
      type: ""
    name: config
