apiVersion: v1
kind: Pod
metadata:
  name: kube-haproxy
  namespace: kube-system
  labels:
    k8s-app: haproxy
    tier: control-plane
spec:
  containers:
  - image: 192.168.1.220/system_containers/haproxy:2.2.24
    imagePullPolicy: IfNotPresent
    name: haproxy
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /stats
        port: 9000
      initialDelaySeconds: 60
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/confd/templates
      name: config
    - mountPath: /etc/kubernetes/pki
      name: pki
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - name: config
    hostPath:
      path: /etc/kubernetes/haproxy
      type: DirectoryOrCreate
  - name: pki
    hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate

