kind: Pod
apiVersion: v1
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: keepalived
    tier: control-plane
  name: kube-keepalived
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-keepalived
    args:
    - --copy-service
    image: 192.168.1.52/k8s.gcr.io/keepalived-amd64:2.0.20
    volumeMounts:
    - mountPath: /container/service/keepalived/assets
      name: config
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
        add:
        - NET_BROADCAST
        add:
        - NET_RAW
  volumes:
  - hostPath:
      path: /etc/kubernetes/keepalived
      type: ""
    name: config
