debug          = false
debug_full     = false
address        = "unix:///var/run/containerd/containerd.sock"
namespace      = "k8s.io"
cni_path       = "/opt/cni/bin"
cni_netconfpath="/etc/cni/net.d/"
cgroup_manager = "systemd"
insecure_registry=true
