#!/bin/sh
set -e

while [ ! -f /usr/local/etc/haproxy/haproxy.cfg  ]; do
  echo "haproxy.cfg file has not been initialized, delayed 5s starting"
  sleep 5
done
echo "haproxy loadbalancer started successfully"

exec 2>&1
HAPROXY=$(/usr/bin/which haproxy)
exec chpst -u haproxy -U haproxy ${HAPROXY} -W -db -f /usr/local/etc/haproxy/haproxy.cfg
