apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - ttl: 0s
nodeRegistration:
  criSocket: {{criSocket}}
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
localAPIEndpoint:
  bindPort: {{bindPort}}
  {{advertiseAddress}}
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: {{kubernetesVersion}}
imageRepository: {{REGISTRY_SERVER}}/{{REGISTRY_USER}}
{{controlPlaneEndpoint}}
{{apiServerUrl}}
{{apiServerCredential}}
{{clusterName}}
apiServer:
  timeoutForControlPlane: 5m0s
  {{certSANs}}
controllerManager:
  extraArgs:
    kube-api-qps: "500"
    kube-api-burst: "200"
    node-monitor-period: 5s
    node-monitor-grace-period: 20s
    node-startup-grace-period: 60s
    pod-eviction-timeout: 1m
    cluster-signing-duration: 876000h0m0s
    concurrent-deployment-syncs: "5"
    concurrent-endpoint-syncs: "5"
    concurrent-gc-syncs: "20"
    concurrent-namespace-syncs: "10"
    concurrent-replicaset-syncs: "5"
    concurrent-service-syncs: "1"
    concurrent-serviceaccount-token-syncs: "5"
    pvclaimbinder-sync-period: 15s
    terminated-pod-gc-threshold: "10"
    profiling: "false"
    {{nodeCidrMaskSize}} 
    {{nodeCidrMaskSizeIPv4}} 
    {{nodeCidrMaskSizeIPv6}}
etcd:
  local:
    dataDir: {{etcdDataDir}}
    extraArgs:
      election-timeout: "5000"
      heartbeat-interval: "500"
      max-request-bytes: "3145728"
      quota-backend-bytes: "8589934592"
    {{serverCertSANs}}
networking:
  plugin: {{networkPlugin}}
  {{podSubnet}}
  {{podExtraSubnet}}
  {{serviceSubnet}}
  {{nodeSubnet}}
  {{dnsDomain}}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: {{kubeProxyMode}}
ipvs:
  strictARP: true
metricsBindAddress: "0.0.0.0"
