apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - ttl: 0s
nodeRegistration:
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
localAPIEndpoint:
  bindPort: {{bindPort}}
  {{advertiseAddress}}
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: {{kubernetesVersion}}
imageRepository: {{REGISTRY_SERVER}}/{{REGISTRY_USER}}
{{controlPlaneEndpoint}}
{{apiServerUrl}}
{{apiServerCredential}}
{{clusterName}}
apiServer:
  timeoutForControlPlane: 5m0s
  {{certSANs}}
etcd:
  local:
    extraArgs:
      election-timeout: "5000"
      heartbeat-interval: "500"
      max-request-bytes: "3145728"
      quota-backend-bytes: "8589934592"
    {{serverCertSANs}}
networking:
  plugin: {{networkPlugin}}
  {{networkMode}}
  {{podSubnet}}
  {{podExtraSubnet}}
  {{serviceSubnet}}
  {{nodeSubnet}}
  {{dnsDomain}}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: {{kubeProxyMode}}
ipvs:
  strictARP: true
metricsBindAddress: "0.0.0.0"
